# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('..'))


# -- Project information -----------------------------------------------------

project = 'Ageas'
copyright = '2026, MaftyLab'
author = 'MaftyLab'

# The short X.Y version
version = ''
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# Mock heavy / optional runtime dependencies so that autodoc can import the
# package on a docs-only environment without a full GPU stack.
autodoc_mock_imports = [
    'torch',
    'pytorch_lightning',
    'torchmetrics',
    'captum',
    'shap',
    'xgboost',
    'sklearn',
    'imblearn',
    'numpy',
    'pandas',
    'anndata',
    'scipy',
    'tqdm',
    'hdf5plugin',
    'h5py',
    'torchnmf',
]
autodoc_default_options = {
    'members': True,           # Document all public methods/attributes
    'undoc-members': False,    # Include methods even if they lack a docstring
    'show-inheritance': False, # Show base classes
    'special-members': '__init__',
    'exclude-members': 'features, label_dict, reverse_label_dict'
}
extensions = [
    'sphinx.ext.autodoc',     # Core library for html generation from docstrings
    'sphinx.ext.autosummary', # Create neat summary tables
    'nbsphinx',
]
autosummary_generate = True   # Turn on sphinx.ext.autosummary
nbsphinx_allow_errors = True
nbsphinx_execute = 'never'
nbsphinx_codecell_lexer = 'python3'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_css_files = [
    'custom.css',
]


# -- Options for HTMLHelp output ---------------------------------------------

htmlhelp_basename = 'Ageasdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Ageas.tex', 'Ageas Documentation',
     'MaftyLab', 'manual'),
]


# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'ageas', 'Ageas Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'Ageas', 'Ageas Documentation',
     author, 'Ageas',
     'AutoML-based Genetic regulatory Element extrAction System.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

epub_title = project
epub_exclude_files = ['search.html']
